rewrite mozo.ui from scratch
mate-desktop/mozo pull request #78
Opened 2021-03-02 21:50 UTC by mbkma

fixing all but one deprecation. The look should be almost identical. The only real change I made is that you can not slide the buttons on the right out of the window.
I wrote this from scratch so I hope I re-added all signals in Glade, would be nice if you could double-check (i.e. check if all buttons, drag and drop, ... work).

2021-03-03 07:27 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">gtk-cancel</property>
We use process-stop as replacement for gtk-cancel.

2021-03-03 07:29 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">gtk-close</property>
We use window-close as replacement for gtk-close.
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-CLOSE:CAPS

2021-03-03 07:30 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">gtk-delete</property>
We use edit-delete as replacement for gtk-delete.
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-DELETE:CAPS

2021-03-03 07:32 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">help</property>
We use help-browser as replacement for gtk-help.
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-HELP:CAPS

2021-03-03 07:35 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">gtk-add</property>
We use list-add as replacement for gtk-add.
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-ADD:CAPS

2021-03-03 07:37 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">gtk-new</property>
We use document-new as replacement for gtk-new.
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-NEW:CAPS

2021-03-03 07:48 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">redo</property>
we use edit-redo
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-REDO:CAPS

2021-03-03 07:51 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">revert</property>
we use document-revert
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-REVERT-TO-SAVED:CAPS

2021-03-03 07:53 UTC, rbuj commented on data/mozo.ui
> +    <property name="icon-name">undo</property>
we use edit-undo
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-UNDO:CAPS

2021-03-03 07:55 UTC, rbuj commented on data/mozo.ui
> +                <property name="icon-name">gtk-dialog-question</property>
we use dialog-question
https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html#GTK-STOCK-DIALOG-QUESTION:CAPS

2021-03-03 10:54 UTC, rbuj requested changes
It upgrades the properties names. It fixes the deprecation of stock buttons. It remove unused ids from mozo.ui. It refactors two functions names.

It unnecessarily maps 3 new response ids returned by the dialog, having a handler.

2021-03-03 10:58 UTC, rbuj approved these changes
LGTM

2021-03-03 11:26 UTC, merged

2021-03-05 03:29 UTC, lukefromdc commented
I just build and installed this, though I did not see this in time to test it pre-merge. Works fine so no problems there. At first I got a fistfull of runtime warnings, but those turned out to come from an invalid entry at the top of the menu. Once that was removed, Mozo worked perfectly.

2022-10-23 19:25 UTC, raveit65 commented
@mbkma 
I got a report about gtk3 version in mozo.ui with Rocky8 distro.
https://bugzilla.redhat.com/show_bug.cgi?id=2136074
For what reason gtk3 version was bumped to 3.24?
Do you think we can lower version to 3.22 ?

Beside from this i got a warning in glade.

![Bildschirmfoto zu 2022-10-23 21-20-47](https://user-images.githubusercontent.com/961604/197411887-5655785b-19d2-4daf-adf6-5f52362a0d18.png)

2022-10-28 20:07 UTC, raveit65 commented
@mbkma 
You are the author of this commit. Is it possible to lower gtk+ required version of mozo.ui ?

2022-10-28 20:22 UTC, mbkma commented
yeah, this were just the standard settings in glade. See https://github.com/mate-desktop/mozo/pull/88.